JS00 ex02 제작 - 메소드 체이닝
42js/js_piscine pull request #17
Opened 2021-06-17 16:03 UTC by hochan222

함수형은 https://github.com/42js/js_piscine/pull/10 에서 이미 잘 만들어져있어서 메소드 체이닝에 초점을 맞췄습니다.

2021-06-20 11:39 UTC, JaeSeoKim reviewed
제목이 재치 있어서 좋은 것 같습니다!!
내용도 메소드 체이님을 확실하게 알 수 있게 잘 설계된 것 같아요!

2021-06-20 11:47 UTC, JaeSeoKim submitted a review, later dismissed

2021-06-20 15:00 UTC, cos18 requested changes
전체적으로 문제가 잘 이해되지 않습니다. exid를 만들어야 하는건가요 아님 exidMethodChaining을 만들어야 하는건가요? 월요일에 이야기 듣고 수정이 필요할 것 같습니다.

2021-06-21 10:33 UTC, Two-Jay commented on js00/ex05.md
> +실행 시 아래 출력 값을 출력하는 함수 `exid`를 작성하세요. 다음과 같은 동작을 하는 함수를 구현해야 합니다.
holee: 맞아요!

2021-06-21 10:36 UTC, Two-Jay commented on js00/ex05.md
> +|   제출할 파일 이름 :     |  upDown.js         |
```suggestion
|   제출할 파일 이름 :     | exid.js         |
```

2021-06-22 16:39 UTC, hochan222 commented on js00/ex05.md
> +실행 시 아래 출력 값을 출력하는 객체 `exid`를 작성하세요. 다음과 같은 동작을 하는 함수를 구현해야 합니다.
```suggestion
실행 시 아래 출력 값을 출력하는 객체 `exid`를 작성하세요. 다음과 같은 동작을 하는 함수를 구현해 exid.js로 제출해야 합니다. 또한 같은 기능을 가진 함수를 메소드 체이닝으로 재구현해 exid-method-chaining.js 로 제출해주세요.
```

2021-06-22 16:39 UTC, hochan222 commented on js00/ex05.md
> +|   제출할 파일 이름 :     | exid.js         |
```suggestion
|   제출할 파일 이름 :     | exid.js, exid-method-chaining.js         |
```

2021-06-22 16:40 UTC, hochan222 commented on js00/ex05.md
> +실행 시 아래 출력 값을 출력하는 객체 `exid`를 작성하세요. 다음과 같은 동작을 하는 함수를 구현해야 합니다.
> 전체적으로 문제가 잘 이해되지 않습니다. exid를 만들어야 하는건가요 아님 exidMethodChaining을 만들어야 하는건가요? 월요일에 이야기 듣고 수정이 필요할 것 같습니다. 

반영

2021-06-28 10:17 UTC, merged