JS01 ex00, ex02 제작
42js/js_piscine pull request #18
Opened 2021-06-18 07:23 UTC by srngch

intra: sarchoi
JS01의 ex00와 ex02 작성했습니다.

2021-06-20 15:13 UTC, JaeSeoKim requested changes
HTML Dom에 대해서 간단한 제어를 쉽게 알아 갈 수 있도록 잘 만들어진 것 같습니다!
하지만 PR 제목에서 설명한 exercise 범위를 벗어난 commit도 같이 포함이 되어 있어서 분리할 필요가 있어보입니다!

1b93b6f, 8c8d105

2021-06-21 01:09 UTC, hochan222 approved these changes
좋은 문제들인것 같아요. 단지 몇몇 문제에서 파일 누락이 보이는데 확인한번해주세요 고생하셨습니다 :)

2021-06-21 01:09 UTC, hochan222 commented on js01/ex00.md
> +아직 `querySelector` 는 사용할 수 없습니다. DOM의 Tree 구조를 사용해 접근해보세요.
```
document.body.main.time.datetime
```

이런식의 접근을 의도한게 맞나요? 맞다면 예시 하나정도는 친절하게 있어도 좋을것같아요 :)

2021-06-21 01:09 UTC, hochan222 commented on js01/ex02.md
> +상품 정보를 입력하면 멤버십 상태에 따라 할인율을 계산하는 페이지를 만드세요. HTML 파일과 JS 파일을 제출해야 합니다. External Javascript를 사용하세요.
아에 처음부터 script tag의 type="module" 로 제한하는것도 좋다고 생각하는데 어떻게 생각하시나요? 아래는 module관련 링크입니다.!

https://ko.javascript.info/modules-intro

2021-06-21 01:09 UTC, hochan222 commented on js01/ex03.md
> +  + getElementBy
종류에따라 getElement 와 getElements 차이가 있어서

getElementByid
getElementsByClassName
getElementsByTagName

등의 시리즈를 나타내는거라면 조금 더 구체적으로 명시해주면 좋을것같아요. (혹은 특정 함수가아닌 시리즈임을 표시.)

2021-06-21 10:47 UTC, JaeSeoKim commented on js01/ex02.md
> +상품 정보를 입력하면 멤버십 상태에 따라 할인율을 계산하는 페이지를 만드세요. HTML 파일과 JS 파일을 제출해야 합니다. External Javascript를 사용하세요.
> 🧐 요런 것도 있다는데 한번 알아보시죠~!
> 요런 느낌으로?

2021-06-22 11:49 UTC, srngch commented on js01/ex00.md
> +아직 `querySelector` 는 사용할 수 없습니다. DOM의 Tree 구조를 사용해 접근해보세요.
추가 완료입니다😄

2021-06-22 11:52 UTC, srngch commented on js01/ex02.md
> +상품 정보를 입력하면 멤버십 상태에 따라 할인율을 계산하는 페이지를 만드세요. HTML 파일과 JS 파일을 제출해야 합니다. External Javascript를 사용하세요.
추가했습니다!! 참고용이라서 '💡 박스'에 링크만 제시했어요.

2021-06-28 10:26 UTC, srngch commented
JS01 ex00, ex02 - 수정 완료!

2021-07-01 04:58 UTC, WONILLISM commented
ex04 문제 수정했습니다.

2021-07-03 13:09 UTC, cos18 reviewed
@WONILLISM 리뷰 확인 부탁드립니다!

2021-07-03 13:09 UTC, cos18 commented on js01/ex04.md
> +  + getElement
위 (ex03)에서 @hochan222 님의 언급대로 getElement의 자세한 언급이 필요하지 않을까요?

2021-07-05 07:30 UTC, JaeSeoKim reviewed
.

2021-07-05 07:47 UTC, JaeSeoKim submitted a review, later dismissed

2021-07-11 12:20 UTC, merged