Be00/ex07 문제제작
42js/js_piscine pull request #48
Opened 2021-07-13 14:13 UTC by Two-Jay

#29 

문제 제작하여 PR 올립니다.
be00/ex07.md 에 올렸습니다.

많이 어렵지 않을까 걱정되긴 합니다만, 수행하는 피시너분들이 morgan 의 소스코드를 참고해도 좋을 거 같습니다.

2021-07-14 11:43 UTC, cos18 requested changes

2021-07-14 11:43 UTC, cos18 commented on be00/ex07.md
> +- 어떤 때에 logger는 모든 정보를 보여주면 좋지만, 어떤 때에는 모든 정보를 안보여주어도 됩니다. 서버에서 logger 함수를 실행할 때 적당하게 추상화하여 유저가 2가지 모드 중 하나를 선택하게 하도록 하는 symple mode를 제공해줍시다. symple mode 에서는 아래의 정보만 제공해야 합니다.
심플모드를 추가한 건 좋은거같아요!

2021-07-14 11:43 UTC, cos18 commented on be00/ex07.md
> +|   제출할 폴더 이름 :     |  ex05                                   |
예제번호 맞춰주세요!

2021-07-14 12:34 UTC, cos18 commented on be00/ex07.md
> +여러분들의 logger를 만들어보고, 이제까지 했던 exercise 들의
문장이 짤려있음

2021-07-19 06:44 UTC, srngch reviewed
morgan에 대한 선지식 유무에 따라서 난이도가 달라질 것 같아요. 난이도가 걱정되신다면 morgan에 대한 힌트를 주는 건 어떨까요? 직접적이지 않더라도 아래처럼 박스에 간접적 메세지로 제시한다던지..

> 💡 기존의 HTTP request logger middleware는 어떻게 작동할까요?

2021-07-21 12:58 UTC, merged