rush01 문제 추가
42js/js_piscine pull request #57
Opened 2021-07-18 14:21 UTC by cos18

인디언 포커 서비스를 구현하는 rush01 문제를 만들었습니다.

2021-07-19 01:50 UTC, MichelleJin12 reviewed
잘 봤습니다~~!! 고생하셨어요~~!!

2021-07-19 11:23 UTC, hochan222 submitted a review, later dismissed
LGTM :)

2021-07-19 11:23 UTC, hochan222 commented on rush01/README.md
> +트럼프 카드를 사용한 심리전, 인디언 포커를 온라인으로 플레이할 수 있는 서비스를 구현해야 됩니다.
> 트럼프 카드를 사용한 심리전, 인디언 포커를

문장 흐름이 부자연스러워 보입니다. 다른 대안은 생각이 나지않아서 리뷰만 남겼습니다.

2021-07-19 11:23 UTC, hochan222 commented on rush01/README.md
> +많은 방법의 룰이 있지만 아래의 방법으로 구현하세요.
```suggestion
아래 명시된 룰을 기준으로 구현해야합니다.
```

2021-07-19 11:23 UTC, hochan222 commented on rush01/README.md
> +
```suggestion
- **상대와 같은 개수 걸기:** 라운드가 종료되고 카드를 오픈합니다. 카드의 숫자가 높은 사람이 승리합니다. 
- **베팅하지 않고 포기하기:** 포기하게되면 무조건 상대 플레이어가 승리합니다.
- **상대보다 많은 개수 걸기:** 라운드를 계속 진행합니다.

```

2021-07-19 11:23 UTC, hochan222 commented on rush01/README.md
> +카드를 오픈 했을 때 같은 숫자가 나온다면 베팅된 칩을 유지한 채 다음 라운드를 진행합니다. (만약 카드가 더이상 없다면 베팅된 칩은 서로 나눠갖게 됩니다.)
```suggestion
카드를 오픈 했을 때 같은 숫자가 나온다면 베팅된 칩을 유지한 채 다음 라운드를 진행합니다. (만약, 카드가 더이상 없다면 베팅된 칩은 서로 나눠갖게 됩니다.)
```

2021-07-19 11:23 UTC, hochan222 commented on rush01/README.md
> +### 전제
```suggestion
### 공통
```

공통의 표현은 어떤가요?

2021-07-19 11:23 UTC, hochan222 commented on rush01/README.md
> +- Oauth 기능이 있는 외부 로그인 / 회원가입 절차를 지원한다.
```suggestion
- OAuth 기능이 있는 외부 로그인 / 회원가입 절차를 지원한다.
```

2021-07-19 11:23 UTC, hochan222 commented on rush01/README.md
> +### 게임
게임도 이런 섹션처럼 세부사항으로 나눠서 분류해도 좋을것같습니다. ex) 채팅, 게임 규칙등..

2021-07-19 12:13 UTC, srngch commented on rush01/README.md
> +트럼프 카드를 사용한 심리전, 인디언 포커를 온라인으로 플레이할 수 있는 서비스를 구현해야 됩니다.
`인디언 포커는 트럼프 카드를 사용한 심리전 게임입니다. 이 게임을 온라인으로 플레이할 수 있는 서비스를 구현해야 됩니다.`

2021-07-19 13:26 UTC, hochan222 commented
### 커멘트

- RUSH 팀을 2명으로 정하기에는 위험성이 너무 크다. 
  - 사람이 많을수록 다양한 의견이 오가고, 프로젝트의 완성도는 높아진다고 생각한다. (구현에만 급급하지않고, 지식을 공부함)
- 양은 많아도 괜찮다고 생각한다. 단지, 본 subject 같은 경우 카테고리별로 잘 분류되어 있지않아 구현 단위를 잡는데 있어서 어려움이 많을것같아 Subject가 원하는 지식을 접하기 전에 기간이 끝날 수 있을것같다. 카테고리별로 분리만 잘하면 문제 없을것같다.

2021-07-19 13:35 UTC, MichelleJin12 commented
- sejin
- 러쉬 인원을 3명 이상으로 늘리는 것 (찬성)
- 웹 개발자를 희망하는 카뎃들이 많기 때문에, 피신이 끝나고도 생각할 거리가 많은, 난이도가 높은 문제를 선호할 수 있다고 생각
- 기본 문제가 아닌 Rush 문제이므로 난이도가 적당하다고 생각
- => 인디언포커 문제 그대로 가도 된다고 생각합니다.

2021-07-20 13:54 UTC, cos18 commented
전 3명 늘리는건 괜찮다고 생각합니다.

만든 사람의 입장에선 서브젝트를 축소하고 싶진 않고, 최대한 유지하는 측면에선 좋습니다.

2021-07-21 05:32 UTC, srngch requested changes

2021-07-21 05:32 UTC, srngch commented on rush01/README.md
> +트럼프 카드를 사용한 심리전, 인디언 포커를 온라인으로 플레이할 수 있는 서비스를 구현해야 됩니다.
인디언 포커는 트럼프 카드를 사용한 심리전 게임입니다. 이 게임을 온라인으로 플레이할 수 있는 서비스를 구현해야 됩니다.

2021-07-21 05:34 UTC, srngch commented on rush01/README.md
> +트럼프 카드를 사용한 심리전, 인디언 포커를 온라인으로 플레이할 수 있는 서비스를 구현해야 됩니다.
```suggestion
인디언 포커는 트럼프 카드를 사용한 심리전 게임입니다. 이 게임을 온라인으로 플레이할 수 있는 서비스를 구현해야 됩니다.
```

2021-07-21 05:57 UTC, srngch commented
- 인원 3명 증가 찬성합니다.
- @hochan222 님의 Subject 정리 의견 찬성합니다. 요구사항 정리 시간을 단축 시켜줄 수 있을 것 같습니다. (ex: 게임 부분에 하위 소제목 추가)

2021-07-21 10:41 UTC, JaeSeoKim commented
인원 3명 으로 증가 시키는 것과, 구현 부분을 단계별로 밟아 갈 수 있도록 세부사항을 분리 및 순서를 정리 시키는 것에 찬성합니다!

2021-07-21 12:47 UTC, Two-Jay commented on rush01/README.md
> +    - 칩 베팅할 때 1개씩 증가 / 감소해야 하며 이에 대해 바로 상대방이 화면을 통해 볼수 있도록 전달해줘야 합니다.
'볼수 있도록' -> '볼 수 있도록'

2021-07-21 12:51 UTC, hochan222 approved these changes

2021-07-21 12:51 UTC, Two-Jay commented on rush01/README.md
> +    - 칩 베팅할 때 1개씩 증가 / 감소해야 하며 이에 대해 바로 상대방이 화면을 통해 볼수 있도록 전달해줘야 합니다.
'볼수 있도록' -> '볼 수 있도록'

2021-07-21 12:51 UTC, Two-Jay commented on rush01/README.md
> +  - 종류는 한가지 이상이 있어야 하고, 기본 로그인 (이메일 / 비밀번호를 입력해 로그인 / 회원가입 하는 절차)는 필수로 구현하지 않아도 된다.
'한가지' -> '한 가지'

2021-07-21 12:51 UTC, Two-Jay commented on rush01/README.md
> +  - 로그인시 메인 페이지에서 위의 두가지 정보를 표시해야 한다.
'두가지' -> '두 가지'

2021-07-21 12:51 UTC, Two-Jay commented on rush01/README.md
> +  - n글자 이상 / 중복 없는 닉네임 정책이 있어야 한다.
n글자 이상 / 중복 없는 닉네임 정책이 있어야 한다. 가 어색한 문장입니다.
'닉네임은 n 글자 이상이어야 하며, 중복이 있어서는 안된다.'

2021-07-21 12:54 UTC, merged